// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABeOWrAbhxoxyOud2BwCLBrTNX_ncPPus',
    appId: '1:930433790939:web:c178ea129ae76c1828edfe',
    messagingSenderId: '930433790939',
    projectId: 'foxautoapp',
    authDomain: 'foxautoapp.firebaseapp.com',
    storageBucket: 'foxautoapp.appspot.com',
    measurementId: 'G-9HSC2SY5HC',

    /* apiKey: "AIzaSyABeOWrAbhxoxyOud2BwCLBrTNX_ncPPus",
    authDomain: "foxautoapp.firebaseapp.com",
    projectId: "foxautoapp",
    storageBucket: "foxautoapp.appspot.com",
    messagingSenderId: "930433790939",
    appId: "1:930433790939:web:c178ea129ae76c1828edfe",
    measurementId: "G-9HSC2SY5HC" */
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApow4a1_AGohZprIOciqpX86idFHQxSLU',
    appId: '1:930433790939:android:81e2c0020098ddb928edfe',
    messagingSenderId: '930433790939',
    projectId: 'foxautoapp',
    storageBucket: 'foxautoapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALj4hHayKdklNI8MxNRhF5CU-1SBuwMvw',
    appId: '1:930433790939:ios:ed617f916846ad3f28edfe',
    messagingSenderId: '930433790939',
    projectId: 'foxautoapp',
    storageBucket: 'foxautoapp.appspot.com',
    iosBundleId: 'com.example.fproject',
  );
}
